[cosmic-ray]
module-path = "eshop.py"
timeout = 20.0
excluded-modules = []
test-command = "pytest test_eshop_fixed.py -v"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.filters.operators-filter]
exclude-operators = [
    "core/NumberReplacer"
] 