name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Start LocalStack
      run: docker-compose up -d

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint

    - name: Run unit tests
      run: |
        pytest tests/unit

    - name: Run integration tests
      run: |
        pytest tests

    - name: Run BDD tests
      run: |
        behave features/

    - name: Generate coverage report
      run: |
        coverage run -m pytest
        coverage report -m

    - name: Teardown Docker
      if: always()
      run: docker-compose down
